spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: USUARIO-SERVICE
          uri: lb://usuario-service
          predicates:
            - Path=/usuarios/**

        - id: HOTEL-SERVICE
          uri: lb://hotel-service
          predicates:
            - Path=/hoteles/**

        - id: CALIFICACIONES-SERVICE
          uri: lb://calificacion-service
          predicates:
            - Path=/calificaciones/**

        - id: AUTH-SERVICE
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

security:
  jwt:
    expiration-in-minutes: 30
    secret-key: ${secret_key}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@localhost:8761/eureka
