spring:
  application:
    name: email-service
  kafka:
    bootstrapServers: http://kafka-server:9092

email:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

management:
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /actuator/usuarios

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}] %m%n"
